<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.7.9 setup script
 * Date: Thu, 08 Mar 2018 22:46:14 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: lastresort [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'lastresort';
$cfg['Servers'][$i]['host'] = 'sqldbforweb.cuc0twrqljlf.us-west-2.rds.amazonaws.com';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'foo';
$cfg['Servers'][$i]['password'] = 'barbarbar';

/* End of servers configuration */

$cfg['blowfish_secret'] = '".}h[Z%&:dMlmEMt7M6S7P(#jzB4j@l2';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>